### ISSUE TITLE
SonarQube Plugin Install

### ISSUE THREAD

**Issue by jayfray12** [redhat-cop/helm-charts#85]
I'm having issues getting any language template plugins installed.  I've got some entries in the `values.yaml` for `plugins.install`.  I see them get put into the `sonarqube-install-plugins` ConfigMap but nothing is installed once SonarQube comes up.  I've looked in the `/opt/sonarqube/extensions/plugins` folder and nothing shows up there.   Any thoughts on what I might be missing?

**Comment by paulbarfuss** [comment]
Jay,

I ran into a similar issue and found that the Helm chart we are using has the initContainers disabled by default. One of these containers is used to `wget` the plugins before the sonarqube container starts. You can re-enable them with `initContainers: true` in your values like in the example below:

```yaml
initContainers: true
plugins:
  install:
    - "https://github.com/sbaudoin/sonar-yaml/releases/download/v1.5.1/sonar-yaml-plugin-1.5.1.jar"
```

Tested with the yaml analyzer listed above and it installed correctly.

At the moment, there is another permissions issue which https://github.com/redhat-cop/helm-charts/pull/86 should resolve for you.
